name: Run -2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      ### DEPENDENCIES ###

      # Hard turn-off interactive mode
      - run: echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

      # Install virtme_ng dependenciest
      - run: sudo apt update
      - run: sudo apt install --yes git qemu-kvm udev iproute2 busybox-static coreutils python3-requests libvirt-clients kbd kmod file rsync zstd udev
      ### END DEPENDENCIES ###

      # Checkout git repository
      - uses: actions/checkout@v4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1.7"
          arch: "x64"      
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
      
      - name: Install virtme-ng and check xanmod kernel version
        run: |
          cd ~
          git clone https://github.com/arighi/virtme-ng.git
          cd virtme-ng
          BUILD_VIRTME_NG_INIT=1 pip install .

      # Setup KVM support
      - name: "KVM support"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Compile Xanmod kernel 
      - name: "Compile Xanmod kernel"
        env:
          CC: $(which clang)
          CXX: $(which clang++)
          LDFLAGS: "-fuse-ld=lld -flto=thin"
        run: |
          sudo cp $(which clang) /usr/bin/cc
          sudo cp $(which clang++) /usr/bin/c++
          sudo cp $(which lld) /usr/bin/ld
          cd ~
          curl -sL https://gitlab.com/xanmod/linux/-/archive/6.16.8-xanmod1/linux-6.16.8-xanmod1.tar.bz2 | tar x --bzip
          cd linux-6.16.8-xanmod1
          ~/virtme-ng/virtme-configkernel --defconfig
          make ARCH=x86 CROSS_COMPILE=x86_64-linux-gnu- -j$(nproc)
          ~/virtme-ng/vng -- uname -r
          
          

          
