name: Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      ### DEPENDENCIES ###

      # Hard turn-off interactive mode
      - run: echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

      # Install XanMod Kernel and virtme_ng dependencies
      - run: |
         wget -qO - https://gitlab.com/afrd.gpg | sudo gpg --dearmor -o /usr/share/keyrings/xanmod-archive-keyring.gpg
         echo 'deb [signed-by=/usr/share/keyrings/xanmod-archive-keyring.gpg] http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-release.list
      - run: sudo apt update
      - run: sudo apt install --yes git qemu-kvm udev iproute2 busybox-static coreutils python3-requests libvirt-clients kbd kmod file rsync zstd udev linux-xanmod-x64v3
      - run: sudo apt install --yes --no-install-recommends dkms libdw-dev clang lld llvm

      ### END DEPENDENCIES ###

      # Checkout git repository
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip

      # Run `uname -r` using a vanilla v6.16 kernel
      - run: |
          cd ~
          git clone https://github.com/arighi/virtme-ng.git
          cd virtme-ng
          BUILD_VIRTME_NG_INIT=1 pip install .
          sudo ./vng -r 6.11.0-1018-azure -- uname -r

      # Setup KVM support
      - name: "KVM support"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Re-run with KVM support
      - name: "Check KVM support"
        run: |
          cd ~/virtme-ng
          clocksource="/sys/devices/system/clocksource/clocksource0/current_clocksource"
          [ "$(sudo ./vng -r 6.11.0-1018-azure -- cat "${clocksource}")" = "kvm-clock" ]
